# More info on config here: https://github.com/golangci/golangci-lint#config-file
run:
  deadline: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - bin

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - ineffassign
    - typecheck
    - dupl
    - goconst
    - gosec

issues:
  exclude-use-default: false
  exclude:
    - G104
    - exported func * returns unexported type *, which can be annoying to use
    - should have a package comment, unless it's in another file for this package
    - don't use an underscore in package name
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv|.*Rollback). is not checked
    - should check returned error before deferring
    - should have comment
